from app.models.knowledge_entry import Intent
from app.services import slot_service

CTU_MAJORS_FROM_FEE_TABLE_2026 = slot_service.MAJOR_CATALOG
MAJOR_ABBREVIATIONS = tuple(slot_service.MAJOR_ABBREVIATIONS)
METHODS = (
    "điểm thi tốt nghiệp THPT", "điểm thi THPT", "học bạ", "điểm học bạ", "V-SAT", "điểm V-SAT", "tuyển thẳng",
    "ưu tiên xét tuyển", "phương thức 5", "xét tuyển thẳng",
)
YEARS = tuple(str(year) for year in range(2019, 2027))

TEMPLATES = {
    Intent.HOI_DIEM_CHUAN: (
        "điểm chuẩn ngành {N} năm {Y} là bao nhiêu",
        "cho em hỏi điểm chuẩn {N} năm {Y}",
        "{N} năm {Y} lấy bao nhiêu điểm",
        "điểm chuẩn {N} xét {P} năm {Y}",
        "ngành {N} năm ngoái bao nhiêu điểm vậy ạ",
        "điểm trúng tuyển ngành {N} là mấy",
        "{N} bao nhiêu điểm thì đậu",
        "năm {Y} điểm chuẩn ngành {N} theo {P} là mấy",
        "em được 24 điểm có đậu ngành {N} không",
        "điểm chuẩn các năm của ngành {N}",
        "mình muốn biết điểm đầu vào ngành {N}",
        "điểm chuẩn {P} ngành {N}",
        "năm {Y} {N} lấy mấy điểm",
        "điểm chuẩn đại học cần thơ năm {Y}",
        "điểm chuẩn ngành {N} có cao không",
        "ngành {N} xét {P} cần bao nhiêu điểm",
        "cho hỏi điểm chuẩn ngành {N}",
        "điểm chuẩn {N} {Y}",
        "{N} điểm chuẩn bao nhiêu vậy ad",
        "năm nay điểm chuẩn ngành {N} bao nhiêu",
        "điểm chuẩn ngành {N} chất lượng cao năm {Y}",
        "xét {P} thì ngành {N} lấy mấy điểm",
        "ngành {N} năm {Y} điểm trúng tuyển bao nhiêu",
        "bao nhiêu điểm thì vào được ngành {N}",
        "điểm chuẩn {N} so với năm {Y} tăng hay giảm",
        "tra cứu điểm chuẩn ngành {N}",
        "em muốn xem điểm chuẩn năm {Y}",
        "điểm chuẩn ngành {N} ở cần thơ",
        "ngành {N} bao nhiêu điểm năm {Y} vậy",
        "điểm chuẩn {P} năm {Y}",
    ),
    Intent.HOI_DIEU_KIEN_TUYEN_SINH: (
        "điều kiện xét tuyển ngành {N} là gì",
        "trường có những phương thức xét tuyển nào",
        "xét {P} cần điều kiện gì",
        "ngành {N} xét tổ hợp môn nào",
        "ngưỡng đầu vào năm {Y} là bao nhiêu",
        "hồ sơ xét tuyển gồm những gì",
        "khi nào hết hạn đăng ký xét tuyển năm {Y}",
        "thí sinh tự do có được xét tuyển không",
        "em thi {P} thì đăng ký như thế nào",
        "điều kiện trúng tuyển năm {Y} là gì",
        "trường tuyển bao nhiêu chỉ tiêu ngành {N}",
        "ngành {N} có xét {P} không",
        "cách tính điểm ưu tiên khu vực như thế nào",
        "tổ hợp xét tuyển ngành {N} năm {Y}",
        "đăng ký nguyện vọng vào trường thế nào",
        "xét tuyển {P} năm {Y} có những điều kiện gì",
        "chỉ tiêu tuyển sinh ngành {N} năm {Y}",
        "làm sao để xét tuyển vào ngành {N}",
        "cần những giấy tờ gì để nhập học",
        "có xét tuyển bằng chứng chỉ IELTS không",
        "phương thức {P} áp dụng cho ngành nào",
        "điều kiện để được tuyển thẳng là gì",
        "khi nào trường công bố kết quả xét tuyển",
        "có được đăng ký nhiều nguyện vọng không",
        "quy đổi điểm {P} như thế nào",
        "ngành {N} có thi năng khiếu không",
        "thủ tục nhập học ngành {N}",
        "xác nhận nhập học trực tuyến ở đâu",
        "thời gian đăng ký xét tuyển {P}",
        "ngành {N} tuyển sinh những khối nào",
    ),
    Intent.HOI_HOC_PHI: (
        "học phí ngành {N} bao nhiêu",
        "học phí năm {Y} là bao nhiêu",
        "một tín chỉ bao nhiêu tiền",
        "học {N} một năm tốn bao nhiêu tiền",
        "học phí chất lượng cao ngành {N}",
        "học phí có tăng hàng năm không",
        "sư phạm có được miễn học phí không",
        "khi nào phải đóng học phí",
        "học phí ngành {N} năm học {Y}",
        "tiền học ngành {N} một năm là bao nhiêu",
        "học phí trường đại học cần thơ năm {Y}",
        "chi phí học ngành {N} có đắt không",
        "học phí mỗi học kỳ khoảng bao nhiêu",
        "ngành {N} học phí bao nhiêu một năm",
        "cho em hỏi học phí ngành {N}",
        "học phí chương trình tiên tiến bao nhiêu",
        "đóng học phí bằng cách nào",
        "học phí có được trả góp không",
        "học phí {N} {Y}",
        "có hỗ trợ học phí cho sinh viên nghèo không",
        "học phí năm nhất ngành {N}",
        "học phí tính theo tín chỉ phải không",
        "học phí ngành {N} có cao hơn ngành {N2} không",
        "một năm học bao nhiêu tiền vậy ạ",
        "mức học phí năm {Y} tăng bao nhiêu",
    ),
    Intent.HOI_QUY_CHE_HOC_VU: (
        "khi nào sinh viên bị cảnh báo học vụ",
        "cần bao nhiêu tín chỉ để tốt nghiệp",
        "điều kiện tốt nghiệp là gì",
        "điểm trung bình bao nhiêu thì bị buộc thôi học",
        "một học kỳ được đăng ký tối đa bao nhiêu tín chỉ",
        "có được học vượt không",
        "xin nghỉ học tạm thời được không",
        "cách tính điểm trung bình tích lũy",
        "rớt môn thì học lại thế nào",
        "xếp loại tốt nghiệp giỏi cần bao nhiêu điểm",
        "chuẩn đầu ra tiếng anh là gì",
        "có được bảo lưu kết quả học tập không",
        "sinh viên có được chuyển ngành không",
        "quy chế học vụ quy định gì về thi lại",
        "học cải thiện điểm được không",
        "thời gian tối đa để hoàn thành chương trình là bao lâu",
        "nghỉ bao nhiêu buổi thì bị cấm thi",
        "điểm rèn luyện có ảnh hưởng tốt nghiệp không",
        "đăng ký học phần như thế nào",
        "có được học song ngành không",
        "điểm chữ A B C D quy đổi sang thang 4 ra sao",
        "bị cảnh báo học vụ mấy lần thì bị đuổi học",
        "làm sao để rút học phần đã đăng ký",
        "quy chế đào tạo tín chỉ của trường",
        "điều kiện nhận học bổng khuyến khích học tập",
        "sinh viên năm cuối cần làm luận văn không",
        "học kỳ hè có bắt buộc không",
        "bao nhiêu điểm thì được xét học bổng",
        "chuẩn đầu ra tin học là gì",
        "quy định về thực tập tốt nghiệp",
        "tổng số tín chỉ của chương trình đào tạo là bao nhiêu",
        "điểm trung bình học kỳ dưới bao nhiêu thì bị cảnh báo",
        "bị buộc thôi học trong trường hợp nào",
        "sinh viên được nợ bao nhiêu tín chỉ",
        "khi nào được xét tốt nghiệp",
        "điều kiện để được công nhận tốt nghiệp sớm",
        "thi rớt môn bắt buộc thì phải làm sao",
        "nghỉ học quá bao lâu thì bị xóa tên",
        "mỗi học kỳ phải đăng ký tối thiểu bao nhiêu tín chỉ",
        "điểm học phần tính như thế nào",
    ),
    Intent.TU_VAN_LO_TRINH: (
        "ngành {N} học những môn gì",
        "tư vấn lộ trình học ngành {N}",
        "học {N} ra trường làm gì",
        "năm nhất ngành {N} học gì",
        "nên chọn ngành {N} hay ngành {N2}",
        "ngành {N} học mấy năm",
        "cơ hội việc làm ngành {N} thế nào",
        "em thích lập trình nên học ngành nào",
        "chương trình đào tạo ngành {N} gồm những gì",
        "muốn làm kỹ sư phần mềm thì học ngành gì",
        "lộ trình 4 năm ngành {N}",
        "học {N} có khó không",
        "ngành {N} phù hợp với người như thế nào",
        "em giỏi toán nên chọn ngành gì",
        "tư vấn giúp em chọn ngành",
        "ngành {N} có những chuyên ngành nào",
        "học {N} cần chuẩn bị kỹ năng gì",
        "ra trường ngành {N} lương bao nhiêu",
        "ngành {N} và ngành {N2} khác nhau thế nào",
        "kế hoạch học tập ngành {N} từng năm",
        "em nên học ngành {N} không",
        "sinh viên ngành {N} thực tập ở đâu",
        "ngành {N} có học tiếng anh chuyên ngành không",
        "muốn làm giáo viên thì học ngành nào",
        "học xong {N} có học lên thạc sĩ được không",
    ),
}

GREETINGS = (
    "xin chào", "chào bạn", "chào ad", "hello", "hi", "chào buổi sáng", "chào buổi tối", "cảm ơn nhiều",
    "cám ơn bạn", "tạm biệt", "bye", "ok cảm ơn", "bạn ơi", "alo", "hế lô", "thanks", "cảm ơn nhé mình hiểu rồi",
    "chào trợ lý", "good morning", "chào em", "cảm ơn ad nhiều nha", "hẹn gặp lại", "mình cảm ơn", "ok rồi",
    "chào anh chị tư vấn", "có ai ở đó không", "xin chào trợ lý tuyển sinh", "cảm ơn bạn đã tư vấn",
)
GREETING_ENDINGS = ("", " ạ", " nhé", "!")

OUT_OF_SCOPE = (
    "hôm nay trời có mưa không", "thời tiết cần thơ ngày mai thế nào", "tỷ số trận MU tối qua",
    "điểm số trận chung kết world cup", "kể chuyện cười đi", "bạn bao nhiêu tuổi", "bạn có người yêu chưa",
    "ai là tổng thống mỹ", "tính giúp 25 nhân 4", "nấu phở như thế nào", "viết code python sắp xếp mảng",
    "dịch câu này sang tiếng anh giúp mình", "giá vàng hôm nay bao nhiêu", "bitcoin tăng hay giảm",
    "mua điện thoại nào tốt", "đặt vé máy bay đi hà nội", "bị cảm cúm uống thuốc gì", "cách giảm cân nhanh",
    "xem phim gì hay", "chơi game gì vui", "hát một bài đi", "làm thơ về mùa thu", "quán cà phê nào đẹp ở ninh kiều",
    "điểm thi ielts của mình có tốt không", "điểm tín dụng ngân hàng là gì", "chấm điểm bài văn giúp mình",
    "cho mình số điện thoại người yêu cũ", "giải phương trình bậc hai", "tiền điện tháng này bao nhiêu",
    "làm sao để nổi tiếng trên tiktok", "chó mèo con nào dễ nuôi hơn", "cách sửa máy giặt",
    "bóng đá việt nam đá khi nào", "điểm danh sách cầu thủ đội tuyển", "học phí khóa học lái xe bao nhiêu",
    "cách nấu cơm ngon", "mấy giờ rồi", "hôm nay là thứ mấy", "gợi ý quà sinh nhật cho bạn gái",
    "chứng khoán hôm nay thế nào", "cách trồng rau sạch tại nhà", "khi nào có bão", "giá xăng hôm nay",
    "viết giúp mình email xin nghỉ việc", "bạn là người hay máy", "kể về lịch sử la mã", "trái đất tròn hay dẹt",
    "cách làm bánh flan", "điểm đến du lịch nào đẹp ở phú quốc", "đội nào vô địch ngoại hạng anh",
    "cách tải nhạc miễn phí", "tỷ giá đô la hôm nay", "ăn gì để đẹp da", "hướng dẫn chơi cờ vua",
    "tại sao bầu trời màu xanh", "bạn thích màu gì", "ca sĩ nào hát hay nhất", "cách hack wifi nhà hàng xóm",
    "điểm karaoke bao nhiêu là hát hay", "tính điểm trung bình môn toán lớp 10 của em trai",
    "nhà hàng nào ngon ở quận 1", "mẹo ngủ ngon", "cách đổi mật khẩu facebook", "ai phát minh ra bóng đèn",
    "iphone mới nhất giá bao nhiêu", "vé xem phim cuối tuần bao nhiêu tiền", "một tô phở ở cần thơ bao nhiêu",
    "vé máy bay tết về hà nội bao nhiêu", "tiền thuê trọ ở ninh kiều bao nhiêu một tháng", "trái đất nặng bao nhiêu",
    "một đô la đổi được bao nhiêu tiền việt", "xe máy điện giá bao nhiêu", "lương lập trình viên mới ra trường bao nhiêu",
    "chiều cao trung bình người việt là bao nhiêu", "nhiệt độ sài gòn hôm nay bao nhiêu độ", "vàng sjc bán ra bao nhiêu",
    "một ngày nên uống bao nhiêu nước", "phí chuyển tiền liên ngân hàng bao nhiêu", "cước gửi hàng ra bắc bao nhiêu",
    "gói cước 4g nào rẻ nhất", "vé xe khách đi sài gòn bao nhiêu", "laptop chơi game tầm bao nhiêu tiền",
    "giá cà phê sữa đá bao nhiêu", "bao nhiêu tuổi thì được lái ô tô", "khi nào có trận derby manchester",
    "khi nào ra mắt iphone mới", "khi nào được nghỉ tết âm lịch", "khi nào mùa nước nổi về miền tây",
    "khi nào nên đi du lịch đà lạt", "khi nào trả lương tháng này", "khi nào có bão về miền trung",
    "khi nào bắt đầu mùa mưa", "khi nào nên tiêm phòng cúm", "khi nào siêu thị mở cửa",
    "bitcoin là gì", "chatgpt là gì", "blockchain là gì", "metaverse là gì", "nft là gì", "lãi kép là gì",
    "cà phê muối là gì", "cảm lạnh là gì", "chứng khoán phái sinh là gì", "hiệu ứng nhà kính là gì",
    "làm bánh mì như thế nào", "cách làm kim chi như thế nào", "đăng ký tài khoản ngân hàng online như thế nào",
    "sửa xe đạp bị xì lốp như thế nào", "chăm sóc cây xương rồng như thế nào", "học bơi như thế nào cho nhanh",
    "cài lại windows như thế nào", "nuôi cá cảnh như thế nào",
)
QUESTION_PREFIXES = ("", "cho em hỏi ", "ad ơi ", "bạn ơi ", "mình muốn hỏi ", "cho mình hỏi ")
QUESTION_ENDINGS = ("", " ạ", " vậy", "?", " ạ?", " nhé")
